name: build-karo
on:
  # push:
  #   branches: 
  #     - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1-5"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: code checkout
        uses: actions/checkout@v4
      - name: build project
        run: mvn install
      - name: upload the artifacts 
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-app
          path: target/*.war
      - name: notify if build fails
        if: failure() # status check function
        run: echo "build is failed! check logs" # use email notification/slack
      
  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Testing project
        run: mvn test
      - name: checkstyle
        run: mvn checkstyle:checkstyle
        
  