name: build-karo
on:
  push:
    branches: 
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1-5"

permissions:
  contents: read # by default worflow gets a read/write access token, restrict it 

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: code checkout
        uses: actions/checkout@v4
      - name: build project
        run: mvn install
      - name: upload the artifacts 
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-app
          path: target/*.war
      - name: notify if build fails
        if: failure() # status check function
        run: echo "build is failed! check logs" # use email notification/slack
      
  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code checkout
        if: github.ref == 'refs/heads/main' 
        uses: actions/checkout@v4
      - name: Testing project
        if: github.ref == 'refs/heads/main'
        run: mvn test
      - name: checkstyle
        run: mvn checkstyle:checkstyle
      - name: invalid branch for testing
        if: github.ref != 'refs/heads/main'
        run: echo "skipping testing!!" 
        
  security_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code chcekout
        uses: actions/checkout@v4

      - name: run security checks
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: .
          format: json
          vuln-type: os,library
          exit-code: 0
          output: trivy-report.json

      - name: upload security checks artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-checks
          path: trivy-report.json
    
  # build_and_publish:
  #   name: 'build and publish'
  #   runs-on: ubuntu-latest
  #   needs: [ 'build', 'Testing', 'security_scan' ]
  #   environment: 'production'
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: code checkout
  #       uses: actions/checkout@v4

  #     - name: configure aws credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with: 
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ vars.AWS_REGION }}

  #     - name: login to amazon ecr
  #       id: login-ecr
  #       uses: uses: aws-actions/amazon-ecr-login@v2

  #     - name: build, tag and push image to ecr
  #       id: build-image
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         IMAGE_TAG: ${{ github.sha }}
  #       run: |
  #         docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

